apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  destination:
    name: ''
    namespace: guestbook
    server: 'https://kubernetes.default.svc'
  source:
    path: guestbook
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    plugin:
      name: polaris-argo
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
syncPolicy:
  automated: {}
